Выполнена разметка
htmlacademy-adaptive/676715-sedona-26 pull request #2
Opened 2022-08-11 14:04 UTC by dinara-k

Выполнена разметка мобильной версии.

2022-08-11 18:49 UTC, summertime-fms requested changes

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +    <header class="main-header">
Давай сократим до просто header.

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +          <h2 class="title-h2">Фото и видео</h2>
наверное лучше title title--h2. в `title` вынесем общее  а в `title--h2` размер и высоту строки конкретно под h2

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +          <p class="main__description">Не можете решиться на путешествие из-за курса? Фотографии помогут вам забыть о политике и экономике.</p>
А где родительский блок main?... Тут лучше секции дать класс например `photos`  и этому параграфу photos__text как вариант

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +        <h3 class="visually-hidden">Список элементов</h3>
Нет необходимости так как уже есть `h2` выше

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +        <ul class="elements__list">
Нет родительского elements. Продолжая плести элементы от photos я предлагаю тут сделать `photos__list`

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +          <li class="elements__item">
Соответственно тут у нас `photos__item` НО помимо этого еще давай карточку сделаем самостоятельным бэм-блоком. Второй класс будет типа `photo-item` ну или как сама решишь назвать. Внутренний блоки будут иметь класс от photo-item

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +            <h4 class="title-h4">Неродные просторы</h4>
если вверху убиаем `h3` то тут уже будет как раз `h3` и классы title title--h3

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +        <div class="text-container sedona-container">
Не совсем понимаю зачем эти классы тут. Это будет просто photos__video-block например. Еще один элемент от секции photos

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +        <div class="text-container sedona-container">
либо выноси в отдельный блок. `video`
И все классы внутри будут от него строится

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +          <button class="video-button" type="button">
button video__button

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +      <b class="sedona__tag">#visitSEDONA</b>
Нет родительского `sedona`. Значит тут лучше main-footer__tag
И давай вместо `main-footer` сделаем просто `footer`

2022-08-11 18:49 UTC, summertime-fms commented on source/catalog.html
> +      <ul class="social__list">
А где родительский social? Тут давай сделаем social + footer__social

2022-08-14 13:58 UTC, summertime-fms requested changes

2022-08-14 13:58 UTC, summertime-fms commented on source/catalog.html
> +        <div class="banner-container">
banner__container. это ж все один блок

2022-08-14 13:58 UTC, summertime-fms commented on source/catalog.html
> +            <p class="photos-video__text description">Автор фото: Борис</p>
точно нужен второй класс тут?..

2022-08-14 13:58 UTC, summertime-fms commented on source/form.html
> +              <input class="form__field review-name" type="text" value="Пётр" id="review-name" name="review-name" placeholder="Введите имя" required>
Второй класс не нужен.

2022-08-14 13:58 UTC, summertime-fms commented on source/form.html
> +              <input class="form__field review-name" type="text" value="Пётр" id="review-name" name="review-name" placeholder="Введите имя" required>
предустановленное value лучше убрать

2022-08-14 13:58 UTC, summertime-fms commented on source/index.html
> +            <div class="text__wrapper">
Две обертки тут ни к чему

2022-08-14 13:58 UTC, summertime-fms commented on source/index.html
> +            <div class="text__wrapper">
и почему блок называется text?..

2022-08-14 13:58 UTC, summertime-fms commented on source/index.html
> +                <p class="advantages__text description">Седона не аттракцион для туристов, там течет своя жизнь</p>
второй класс не нужен

2022-08-14 16:53 UTC, dinara-k commented on source/index.html
> +            <div class="text__wrapper">
Планирую сделать так:
.advantages-item {
  display: flex;
  flex-wrap: wrap;
  }

.text {
  color: #ffffff;
  background-color: #83B3D3;
}

Называется text, т.к. не знала как по-другому назвать)

2022-08-14 16:55 UTC, dinara-k commented on source/index.html
> +                <p class="advantages__text description">Седона не аттракцион для туристов, там течет своя жизнь</p>
Планирую делать так:
.advantages-text {
    margin: 0;
}

description {
  font-size: 18px;
  line-height: 21px;
  text-align: center;
}

2022-08-14 17:11 UTC, dinara-k commented on source/catalog.html
> +            <p class="photos-video__text description">Автор фото: Борис</p>
Планирую сделать так:
.photos-video__text {
    margin: 0;
}

.photos-video__item .description {
     font-size: 22px;
     line-height: 36px;
     font-weight: 400;
     color: #333333;
     background-color: #ffffff;
}

2022-08-15 07:52 UTC, merged